"""Git gate — creates GitHub PRs for experiment promotions."""
from __future__ import annotations

import subprocess

from src.core.logging import get_logger

log = get_logger(__name__)


def create_pr_for_experiment(experiment_id: str, scorecard: dict) -> str:
    """Use subprocess to run: gh pr create --title ... --body ...

    Returns PR URL string, or 'PR: none — <reason>' on failure.
    """
    sharpe = scorecard.get("sharpe", "n/a")
    total_return = scorecard.get("total_return", "n/a")
    max_dd = scorecard.get("max_drawdown", "n/a")

    title = f"experiment: promote {experiment_id[:8]}"
    body = (
        f"## AutoResearch Experiment: `{experiment_id}`\n\n"
        f"### Scorecard\n"
        f"| Metric | Value |\n"
        f"|--------|-------|\n"
        f"| Sharpe | {sharpe} |\n"
        f"| Total Return | {total_return} |\n"
        f"| Max Drawdown | {max_dd} |\n\n"
        f"*Generated by AutoResearch Engine (Unit 13)*"
    )

    cmd = [
        "gh", "pr", "create",
        "--title", title,
        "--body", body,
    ]

    log.info("create_pr_for_experiment", experiment_id=experiment_id, cmd=cmd)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            log.info("pr_created", url=url)
            return url
        else:
            reason = result.stderr.strip() or result.stdout.strip() or "unknown error"
            log.warning("pr_create_failed", reason=reason, returncode=result.returncode)
            return f"PR: none — {reason}"
    except subprocess.TimeoutExpired:
        log.error("pr_create_timeout")
        return "PR: none — subprocess timed out"
    except FileNotFoundError:
        log.error("gh_not_found")
        return "PR: none — gh CLI not found"
    except Exception as exc:
        log.error("pr_create_exception", error=str(exc))
        return f"PR: none — {exc}"
